Repository KhronosGroup/Vulkan-ValidationLayers, pull requests merged in 2022-12, with the labels that each got.

#4888 ci: Build against latest MacOS SDK
  .github/workflows/build_macos.yml
Labels: Build

#4908 docs: Remove 'CMake Generators' section
  BUILD.md
Labels: Documentation

#4907 ci: Test Xcode/Ninja/CMakePresets.json on MacOS CI
  .github/workflows/build_macos.yml
  scripts/update_deps.py
Labels: Build

#4915 cmake: Fix MINGW build
  CMakeLists.txt
  layers/CMakeLists.txt
Labels: Build

#4942 cmake: Fixup usage of BINARY_DIR
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: Build

#4962 layers: Expose Imagination Technologies best practice in manifest
  layers/json/VkLayer_khronos_validation.json.in
Labels: BestPractices

#4991 tests: Check developer environment variables
  .github/workflows/build_macos.yml
  tests/vktestframework.cpp
Labels: Enhancement
