Repository KhronosGroup/Vulkan-ValidationLayers, pull requests merged in 2022-11, with the labels that each got.

#4740 cmake: Add toolchain file support to update_deps.py
  BUILD.md
  CMakeLists.txt
  scripts/update_deps.py
Labels: Build

#4785 build: Fix MSVC GN build
  BUILD.gn
Labels: Build

#4786 build: Remove Android dependency on Vulkan-Tools
  build-android/jni/Android.mk
  build-android/known_good.json
  build-android/update_external_sources_android.bat
  tests/layer_validation_tests.h
Labels: Build, Android

#4787 cmake: Cleanup layers/CMakeLists.txt
  CMakeLists.txt
  layers/CMakeLists.txt
Labels: Build

#4806 cmake: Install during CI builds
  .github/workflows/build_macos.yml
  scripts/common_ci.py
Labels: Enhancement

#4813 cmake: Avoid duplicate VkLayer_khronos_validation.json
  layers/CMakeLists.txt
Labels: Build

#4819 cpp: Use std::make_unique (C++14)
  layers/gpu_utils.cpp
  layers/pipeline_sub_state.cpp
  layers/queue_state.cpp
  layers/render_pass_state.cpp
  layers/state_tracker.cpp
  layers/synchronization_validation.cpp
  layers/vk_layer_data.h
  tests/positive/pipeline.cpp
  tests/positive/sync.cpp
  tests/vklayertests_best_practices.cpp
  tests/vklayertests_others.cpp
  tests/vklayertests_pipeline_shader.cpp
  tests/vkrenderframework.cpp
  tests/vksyncvaltests.cpp
Labels: Enhancement

#4817 cmake: Simplify profile layer CMake code
  tests/layers/CMakeLists.txt
  tests/layers/VkLayer_device_profile_api.json.in
  tests/layers/linux/VkLayer_device_profile_api.json
  tests/layers/macos/VkLayer_device_profile_api.json
  tests/layers/windows/VkLayer_device_profile_api.json
Labels: Build

#4834 cmake: Remove mk_layer_config_dir
  layers/CMakeLists.txt
Labels: Build

#4837 cmake: Layers should be MODULE instead of SHARED
  layers/CMakeLists.txt
  tests/layers/CMakeLists.txt
Labels: Enhancement, Build

#4844 cmake: Fix incorrect install location
  layers/CMakeLists.txt
Labels: Build

#4850 cmake: Fix incorrect else() argument warning
  layers/CMakeLists.txt
Labels: Build

#4842 manifest: improve warn robust oob setting dependency
  layers/json/VkLayer_khronos_validation.json.in
Labels: Enhancement, GPU-AV

#4886 macos: Remove sprintf
  tests/vklayertests_pipeline_shader.cpp
Labels: Build
