Repository KhronosGroup/Vulkan-ValidationLayers, pull requests merged in 2023-11, with the labels that each got.

#6966 android: Document nodelete performance benefits
  tests/android/CMakeLists.txt
Labels: Android

#6965 scripts: Allow running tests on Mac
  scripts/common_ci.py
Labels: Apple

#6985 GitHub actions cleanup linux CI runs
  .github/workflows/vvl.yml
Labels: CI/Tests, Cleanup

#7042 layers: Fix upcoming VUID in 272
  layers/core_checks/cc_query.cpp
  layers/stateless/sl_cmd_buffer.cpp
  tests/unit/query.cpp
  tests/unit/video.cpp
Labels: VUID Churn
