Repository KhronosGroup/Vulkan-ValidationLayers, pull requests merged in 2023-04, with the labels that each got.

#5563 docs: Cleanup README.md
  README.md
Labels: Documentation

#5562 docs: Remove implication of 18.04 build support
  BUILD.md
Labels: Build, Documentation

#5569 build: Fix enum conversions
  layers/CMakeLists.txt
  tests/CMakeLists.txt
  tests/layers/CMakeLists.txt
  tests/negative/descriptors.cpp
  tests/negative/sparse.cpp
Labels: Build

#5599 android: Remove VK_PROTOTYPES define
  build-android/cmake/layerlib/CMakeLists.txt
  build-android/jni/Android.mk
Labels: Build, Android

#5613 android: Ensure important Android NDK variables are propogated
  .github/workflows/vvl.yml
  scripts/CMakeLists.txt
Labels: Build, Android

#5626 cmake: Only run update_deps.py during configure step
  scripts/CMakeLists.txt
Labels: Build

#5641 docs: Community Assistance
  README.md
Labels: Documentation

#5638 ci: Speed up Android CI for Android.mk build
  .github/workflows/vvl.yml
  scripts/github_ci_android.py
Labels: Android, CI/Tests

#5654 docs: Vulkan Validation Layers (VVL)
  README.md
Labels: Documentation

#5666 gpu: Use HOST_CACHED memory for descriptor set and bda state
  layers/gpu_validation/gpu_validation.cpp
Labels: Performance, GPU-AV

#5679 cmake: Fixup tests/CMakeLists.txt for Android
  tests/CMakeLists.txt
Labels: Build, Android

#5699 bp: Log BestPractices-SemaphoreCount as informational
  layers/best_practices/bp_instance_device.cpp
  tests/negative/best_practices.cpp
Labels: BestPractices

#5720 bp: Rename logging helper functions
  layers/best_practices/best_practices_utils.cpp
  layers/best_practices/best_practices_validation.h
  layers/generated/best_practices.cpp
  scripts/best_practices_generator.py
Labels: BestPractices

#5717 android: Remove build-android/cmake
  build-android/cmake/README.md
  build-android/cmake/layerlib/CMakeLists.txt
  build-android/cmake/layerlib/build.gradle
  build-android/cmake/layerlib/proguard-rules.pro
  build-android/cmake/layerlib/src/main/AndroidManifest.xml
  build-android/cmake/layerlib/src/main/res/values/strings.xml
Labels: Android

#5713 layers: Revert ActiveSlot mapping type
  layers/core_checks/cc_descriptor.cpp
  layers/core_checks/core_validation.h
  layers/state_tracker/cmd_buffer_state.h
  layers/state_tracker/pipeline_state.cpp
  layers/state_tracker/pipeline_state.h
Labels: Performance

#5729 android: Create android_hardware_buffer.h
  tests/CMakeLists.txt
  tests/framework/android_hardware_buffer.h
  tests/framework/test_framework_android.cpp
  tests/framework/test_framework_android.h
  tests/negative/android_hardware_buffer.cpp
  tests/positive/android_hardware_buffer.cpp
Labels: Build, Android

#5731 docs: Cleanup Windows build instructions
  BUILD.md
Labels: Documentation

#5752 DebugReporter cleanup
  layers/generated/lvt_function_pointers.cpp
  scripts/lvt_file_generator.py
  tests/framework/error_monitor.cpp
  tests/framework/error_monitor.h
  tests/framework/layer_validation_tests.cpp
  tests/framework/render.cpp
  tests/framework/render.h
  tests/positive/other.cpp
Labels: CI/Tests
