Repository KhronosGroup/Vulkan-ValidationLayers, pull requests merged in 2023-03, with the labels that each got.

#5391 cmake: Enable MSVC warnings 4189 and 5038 consistently
  CMakeLists.txt
  layers/CMakeLists.txt
Labels: Build

#5392 ci: Warnings as errors for MinGW build
  .github/workflows/vvl.yml
Labels: CI/Tests

#5393 repo: Link to wikipedia minimum reproducible example
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Documentation

#5394 cmake: Fix VkLayer_utils missing-field-initializers warnings
  layers/CMakeLists.txt
  layers/generated/vk_typemap_helper.h
  scripts/helper_file_generator.py
Labels: Build

#5427 ci: Modernize CMake usage in CI scripts
  .github/workflows/vvl.yml
  scripts/common_ci.py
  scripts/github_ci_win_linux.py
Labels: Build, CI/Tests

#5444 ci: Install Release loader/profiles/mockicd
  scripts/common_ci.py
  scripts/github_ci_build_desktop.py
  scripts/github_ci_win_linux.py
Labels: CI/Tests

#5451 build: Compile vma/xxhash as system include directories
  BUILD.gn
  build-android/cmake/layerlib/CMakeLists.txt
  build-android/jni/Android.mk
  layers/CMakeLists.txt
  layers/core_checks/shader_validation.cpp
  layers/error_message/logging.cpp
  layers/external/vma/vk_mem_alloc.h
  layers/external/vma/vma.cpp
  layers/external/vma/vma.h
  layers/gpu_validation/gpu_utils.cpp
  layers/gpu_validation/gpu_utils.h
  layers/layer_options.cpp
Labels: Build

#5460 layers: Fix DrawDispatchVuid copy
  layers/core_checks/cmd_buffer_dynamic_validation.cpp
  layers/core_checks/drawdispatch_validation.cpp
  layers/core_checks/pipeline_validation.cpp
  layers/core_checks/ray_tracing_validation.cpp
Labels: Performance

#5420 Layer generic layer settings
  layers/VkLayer_khronos_validation.json.in
  layers/layer_options.cpp
Labels: Enhancement

#5489 docs: Simplify Building Overview
  BUILD.md
Labels: Documentation

#5523 cmake: Add VVL_CODEGEN
  CMakePresets.json
  docs/generated_code.md
  layers/CMakeLists.txt
  scripts/generate_source.py
Labels: Build

#5531 layers: Fix VkLayerTest.ViewportSwizzleNV
  layers/stateless/parameter_validation_utils.cpp
  tests/negative/pipeline_shader.cpp
  tests/positive/pipeline.cpp
Labels: CI/Tests
