Repository KhronosGroup/Vulkan-ValidationLayers, pull requests merged in 2023-05, with the labels that each got.

#5755 layers: Remove under specified shader_float_control
  layers/core_checks/cc_shader.cpp
Labels: SpecChange

#5759 android: Build vk_layer_validation_tests as a MODULE library
  tests/CMakeLists.txt
  tests/android/README.md
Labels: Build, Android, CI/Tests

#5761 layers: Cleanup various CUBE_COMPATIBLE_BIT validation
  layers/core_checks/cc_image.cpp
  layers/stateless/sl_image.cpp
  tests/negative/image.cpp
Labels: CI/Tests

#5786 ci: Enable LOADER_DISABLE_DYNAMIC_LIBRARY_UNLOADING on WIN32
  scripts/common_ci.py
Labels: CI/Tests

#5780 docs: Remove outdated GetDeviceProcAddr example usage
  docs/creating_tests.md
Labels: Documentation

#5778 gpu: Split descriptor set status into separate buffers
  build-android/known_good.json
  docs/gpu_validation.md
  layers/generated/spirv_tools_commit_id.h
  layers/gpu_validation/gpu_utils.cpp
  layers/gpu_validation/gpu_utils.h
  layers/gpu_validation/gpu_validation.cpp
  layers/gpu_validation/gpu_validation.h
  scripts/known_good.json
  tests/framework/layer_validation_tests.cpp
  tests/negative/gpu_av.cpp
  tests/positive/gpu_av.cpp
Labels: GPU-AV

#5816 tests: Move Positive tests to separate files
  build-android/jni/Android.mk
  tests/CMakeLists.txt
  tests/positive/command.cpp
  tests/positive/descriptors.cpp
  tests/positive/image.cpp
  tests/positive/other.cpp
  tests/positive/pipeline.cpp
  tests/positive/pipeline_topology.cpp
  tests/positive/protected_memory.cpp
  tests/positive/render_pass.cpp
  tests/positive/shader_compute.cpp
  tests/positive/shader_interface.cpp
  tests/positive/shader_limits.cpp
  tests/positive/shader_push_constants.cpp
  tests/positive/shader_spirv.cpp
  tests/positive/shader_storage_image.cpp
  tests/positive/shader_storage_texel.cpp
  tests/positive/shaderval.cpp
  tests/positive/wsi.cpp
Labels: Cleanup

#5821 tests: Add positive for 1.3 memory requirements functionality
  tests/positive/memory.cpp
Labels: CI/Tests

#5834 tests: Add NegativeDescriptorBuffer.NullHandle
  tests/negative/descriptor_buffer.cpp
Labels: CI/Tests

#5837 bp: Remove best practice warnings generating false positives
  layers/best_practices/best_practices_error_enums.h
  layers/best_practices/bp_device_memory.cpp
Labels: BestPractices

#5839 layers: Cleanup memory_requirements_checked code
  layers/state_tracker/buffer_state.cpp
  layers/state_tracker/buffer_state.h
  layers/state_tracker/image_state.cpp
  layers/state_tracker/image_state.h
  layers/state_tracker/state_tracker.cpp
  layers/state_tracker/state_tracker.h
Labels: Cleanup

#5862 android: Fix and test exported Android functions
  .github/workflows/vvl.yml
  tests/android/CMakeLists.txt
Labels: Build, Android

#5869 tests: Add PositiveImage.CreateDrmImageWithExternalMemory
  tests/positive/image.cpp
Labels: CI/Tests

#5883 android: Cleanup Android CMake code
  layers/android/CMakeLists.txt
  tests/CMakeLists.txt
  tests/android/CMakeLists.txt
Labels: Android

#5888 scripts: Clean fetched dependencies on new configuration
  scripts/CMakeLists.txt
  scripts/update_deps.py
Labels: Enhancement, Build

#5890 docs: Show usage of Vendor Specific Best Practices
  layers/vk_layer_settings.txt
Labels: BestPractices, Documentation

#5904 Use ccache for MinGW
  .github/workflows/vvl.yml
Labels: CI/Tests

#5905 scripts: Enable testing script on Windows
  scripts/common_ci.py
  scripts/github_ci_win_linux.py
Labels: CI/Tests

#5910 Fixed rtti settings for chromium builds.
  BUILD.gn
Labels: Build

#5916 ci: Fix linux performance
  .github/workflows/vvl.yml
Labels: CI/Tests
