Repository KhronosGroup/Vulkan-ValidationLayers, pull requests merged in 2023-09, with the labels that each got.

#6417 android: Remove strings.xml
  tests/android/res/values/strings.xml
Labels: Build, Android, Cleanup

#6468 cmake: Remove BUILD_LAYER_SUPPORT_FILES
  .github/workflows/vvl.yml
  CMakeLists.txt
  layers/CMakeLists.txt
  tests/integration/CMakeLists.txt
  tests/integration/main.cpp
Labels: Build, CI/Tests, Cleanup

#6443 layer: Clean up layer settings code
  layers/layer_options.cpp
Labels: Cleanup

#6528 gn: Generate .gn file
  .gitignore
  .gn
  scripts/gn/update_deps.sh
Labels: Build, Cleanup

#6538 layers: Remove unused code
  layers/vk_layer_config.cpp
  layers/vk_layer_config.h
Labels: Cleanup

#6544 cmake: Fix FetchContent usage
  CMakeLists.txt
  layers/CMakeLists.txt
Labels: Build
