Repository KhronosGroup/Vulkan-ValidationLayers, pull requests merged in 2023-01, with the labels that each got.

#5032 cmake: Raise minimum to 3.17.2
  BUILD.md
  CMakeLists.txt
  scripts/cmake_test_min.py
Labels: Build

#5034 cmake: Use target_link_options/add_link_options
  CMakeLists.txt
  layers/CMakeLists.txt
  tests/CMakeLists.txt
  tests/layers/CMakeLists.txt
Labels: Build

#5044 cmake: Cleanup VkLayer_utils
  CMakeLists.txt
  layers/CMakeLists.txt
Labels: Build, Documentation

#5041 github: Add CODEOWNERS
  .github/CODEOWNERS
Labels: Documentation

#5062 cmake: Delete VVLGenerateSourceCode.cmake
  CMakeLists.txt
  cmake/VVLGenerateSourceCode.cmake
  layers/CMakeLists.txt
Labels: Build

#5087 cmake: Fix usage of Vulkan::Registry
  layers/CMakeLists.txt
  scripts/known_good.json
Labels: Build

#5091 cmake: Fix LunarG/VulkanTools build
  CMakeLists.txt
  layers/CMakeLists.txt
  tests/CMakeLists.txt
Labels: Build

#5094 cmake: Add VVL_ENABLE_TSAN
  CMakeLists.txt
Labels: Enhancement, Build

#5099 cmake: Use target_compile_definitions & add_compile_definitions
  CMakeLists.txt
  layers/CMakeLists.txt
Labels: Build

#5109 docs: Remove mention of travis
  scripts/update_deps.py
Labels: Documentation

#5117 ci: Test CMake min with GitHub action
  .github/workflows/build_linux.yml
  scripts/cmake-format.py
  scripts/cmake_test_min.py
Labels: Build, CI/Tests

#5118 build: Remove VS2015 support
  BUILD.md
  layers/CMakeLists.txt
  tests/vktestframework.cpp
Labels: Build, Documentation

#5122 macos: Target 10.15
  .github/workflows/build_macos.yml
  BUILD.md
  layers/image_state.cpp
Labels: Build, CI/Tests

#5130 docs: Notify users about upcoming change
  README.md
Labels: Documentation

#5131 cmake: Create scripts/CMakeLists.txt
  CMakeLists.txt
  scripts/CMakeLists.txt
  tests/CMakeLists.txt
Labels: Build

#5142 macos: Require VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME
  tests/positive/other.cpp
  tests/vklayertests_others.cpp
  tests/vkrenderframework.cpp
Labels: CI/Tests

#5144 scripts: Check that LunarG / Valve Copyright is updated
  scripts/check_code_format.py
Labels: Documentation

#5152 github: Use main instead of master
  .github/workflows/build_android.yml
  .github/workflows/build_linux.yml
  .github/workflows/build_linux_gn.yml
  .github/workflows/build_macos.yml
  .github/workflows/build_windows.yml
  BUILD.md
  CONTRIBUTING.md
  LAYER_CONFIGURATION.md
  README.md
  docs/debug_printf.md
  docs/generated_code.md
  docs/gpu_validation.md
  layers/shader_instruction.h
  layers/vk_layer_config.cpp
  scripts/check_code_format.py
  scripts/update_deps.py
  tests/README.md
  tests/layer_validation_tests.cpp
Labels: Documentation, CI/Tests

#5154 ci: Fix MacOS CI warning
  .github/workflows/build_macos.yml
  tests/vklayertests_pipeline_shader.cpp
Labels: CI/Tests, Apple

#5158 build: Fix duplicate xxhash object files
  BUILD.gn
  CMakeLists.txt
  build-android/cmake/layerlib/CMakeLists.txt
  build-android/jni/Android.mk
  layers/CMakeLists.txt
  layers/xxhash.cpp
Labels: Build

#5160 scripts: Cleanup update_deps `CMakeBuild` step
  scripts/update_deps.py
Labels: Build

#5162 build: Update 'api_version' via `generate_source.py`
  build-gn/generate_vulkan_layers_json.py
  layers/CMakeLists.txt
  layers/json/VkLayer_khronos_validation.json.in
  scripts/generate_source.py
  tests/layers/CMakeLists.txt
  tests/layers/VkLayer_device_profile_api.json.in
Labels: Build

#5166 gn: Remove deprecated vulkan_core.h parsing
  BUILD.gn
  build-gn/generate_vulkan_layers_json.py
Labels: Build

#5174 gn: Fix GN GitHub action
  .github/workflows/build_linux.yml
  .github/workflows/build_linux_gn.yml
  .gitignore
  README.md
  build-gn/DEPS
Labels: CI/Tests

#5170 Remove -fno-strict-aliasing and -fno-builtin-memcmp #5161
  CMakeLists.txt
  layers/cast_utils.h
  layers/generated/chassis.h
  layers/generated/layer_chassis_dispatch.cpp
  layers/gpu_validation/gpu_validation.cpp
  scripts/layer_chassis_dispatch_generator.py
  scripts/layer_chassis_generator.py
  tests/CMakeLists.txt
  tests/vklayertests_buffer_image_memory_sampler.cpp
  tests/vklayertests_descriptor_renderpass_framebuffer.cpp
  tests/vklayertests_pipeline_shader.cpp
  tests/vklayertests_ray_tracing_pipeline.cpp
Labels: Build

#5186 cmake: Check MSVC before installing PDB file
  layers/CMakeLists.txt
Labels: Build

#5192 gn: Add Ninja to DEPS
  build-gn/DEPS
Labels: Build
