Repository KhronosGroup/Vulkan-ValidationLayers, pull requests merged in 2023-12, with the labels that each got.

#7081 layers: Fix 272 VUID Churn
  layers/core_checks/cc_render_pass.cpp
  tests/unit/renderpass.cpp
Labels: VUID Churn

#7087 ci: Remove MacOS from CI
  .github/workflows/vvl.yml
Labels: CI/Tests

#7090 cmake: Fix CMAKE_REQUIRE_FIND_PACKAGE_VulkanHeaders has no effect
  scripts/CMakeLists.txt
Labels: Build

#7095 scripts: Move TSAN blacklist into C++ code instead of script
  scripts/common_ci.py
  tests/framework/layer_validation_tests.h
  tests/unit/command.cpp
  tests/unit/other_positive.cpp
  tests/unit/query_positive.cpp
  tests/unit/sync_object_positive.cpp
  tests/unit/sync_val.cpp
  tests/unit/viewport_inheritance.cpp
Labels: CI/Tests

#7112 ci: Update to macos-12 for iOS build
  .github/workflows/vvl.yml
Labels: CI/Tests

#7098 docs: Update layer configuration documentation
  docs/gpu_validation.md
  docs/khronos_validation_layer.md
Labels: Documentation

#7206 gn: Cleanup chromium scripts
  .github/workflows/vvl.yml
  scripts/gn.py
  scripts/gn/gn.py
Labels: CI/Tests
